server:
  port: 8080

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://192.168.18.33:8761/eureka/
  instance:
    hostname: localhost
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: customer-service
          uri: http://192.168.18.33:9000
          predicates:
            - Path=/customer/**
        - id: product-service
          uri: http://192.168.18.33:9003
          predicates:
            - Path=/product/**
        - id: movement-service
          uri: http://192.168.18.33:9005
          predicates:
            - Path=/movement/**
        - id: benefit-service
          uri: http://192.168.18.33:9007
          predicates:
            - Path=/benefit/**