server:
  port: 9005
  error:
    include-message: always
    include-binding-errors: always
spring:
  data:
    mongodb:
      uri: mongodb+srv://nttdata-admin:NCZ6V3pnN_QB9V.@bootcamp-nttdata-001.0qsps.mongodb.net/bootcamp
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.18.33:8761/eureka/